#!/bin/bash

echo "========================================="
echo "RLS Fix Migration for Quality Checklists"
echo "========================================="
echo ""
echo "This migration fixes the Row Level Security (RLS) policies for the quality_checklist_templates table."
echo ""
echo "The main issue was that the RLS policies were comparing workers.id with auth.uid(),"
echo "but they should be comparing workers.auth_user_id with auth.uid()."
echo ""
echo "To apply this migration manually:"
echo ""
echo "1. Go to your Supabase SQL Editor:"
echo "   https://supabase.com/dashboard/project/zvqszimyodijulqpkbub/sql/new"
echo ""
echo "2. Copy and run the contents of:"
echo "   supabase/migrations/20250616000001_fix_quality_checklist_rls.sql"
echo ""
echo "3. After applying the migration, test the checklist manager again at:"
echo "   http://localhost:3000/admin/checklists"
echo ""
echo "What this fixes:"
echo "- ✅ Managers/admins can now properly create checklist items"
echo "- ✅ The is_required field will be saved correctly"
echo "- ✅ All CRUD operations will work with proper permissions"
echo ""
echo "If you still have issues after applying this migration:"
echo "1. Check the browser console for detailed error messages"
echo "2. Verify you're logged in as a manager or admin"
echo "3. Check for duplicate items (unique constraint violation)"
echo ""
echo "Press any key to open the SQL editor in your browser..."
read -n 1 -s

# Open the Supabase SQL editor
open "https://supabase.com/dashboard/project/zvqszimyodijulqpkbub/sql/new"